### ISSUE TITLE
Missing full stop punctuation 

### ISSUE THREAD

**Issue by sutini** [sutini/allyapp#3]
tested on iPhone 6 iOS 8.3 
current App Store version

steps: 
1. tap on the 'More' icon on the UITabBar
2. tap on 'Feedback? Ideas? Live Support' in the 'Setting' screen 
3. tap on 'Features' 
4. tap on 'How does the results page work?' 

result: 
• Missing the full stop punctuation 
![img_9861](https://cloud.githubusercontent.com/assets/649372/8374879/27483410-1bf9-11e5-8e63-1e86de16a563.PNG)

**Comment by g-hen** [comment]
fixed- thank you!

**Comment by sutini** [comment]
your most welcome! issue closed.
