### ISSUE TITLE
Text error: circumflex symbol in the sentence 

### ISSUE THREAD

**Issue by sutini** [sutini/allyapp#4]
tested on iPhone 6 iOS 8.3 
current App Store version

steps: 
1. tap on the 'More' icon on the UITabBar
2. tap on 'Feedback? Ideas? Live Support' in the 'Setting' screen 
3. tap on 'Which cities does ally work in?'
4 tap on 'ally isn't in my city(yet!). What shall I do?' 

result: 
• the circumflex symbol seems out of place in the sentence. 
![img_9857](https://cloud.githubusercontent.com/assets/649372/8375535/47138f24-1bfe-11e5-9e88-f4db54a4b766.PNG)

**Comment by g-hen** [comment]
I originally included this on purpose, but have removed it now. thanks!
