### ISSUE TITLE
Text error: added spacing in the sentence 

### ISSUE THREAD

**Issue by sutini** [sutini/allyapp#5]
tested on iPhone 6 iOS 8.3 
current App Store version

steps: 
1. tap on the 'More' icon on the UITabBar
2. tap on 'Feedback? Ideas? Live Support' in the 'Setting' screen 
3. tap on 'Miss the live and local feature?' 

result: 
![img_9863](https://cloud.githubusercontent.com/assets/649372/8376061/5f15259c-1c03-11e5-81ed-9f0b3e2035c6.PNG)

**Comment by g-hen** [comment]
fixed!

**Comment by sutini** [comment]
Great! I will close this issue.
